---
# this playbook deploys my config files which i also keep in the same git repo

- hosts: localhost
  vars_files:
    - vars
  vars:
    - home_dir: "{{lookup('env','HOME')}}"
    - files_dir: "{{dots}}"

  tasks:

  - name: symlink every file into specified destination
    file:
      mode: 0644
      src: "{{files_dir}}/{{item.name}}"
      dest: "{{item.path}}/{{item.name}}"
      state: link
    with_items: "{{dotfiles_definitions}}"

